import Question from "./UtilityComponets/Question";

export default function Faq() {
  return (
    <div id="WrapperFaq">
      <h1 id="FaqHeader">Frequently asked Questions</h1>
      <Question
        question={"Who built this site?"}
        text={"Hey im Sam, a Software Engineer, and long suffering Mets fan"}
      />
      <Question
        question={"What Stack does the site run on?"}
        text={
          "Currently it's a React frontend with Python/Flask on the Backend. Postgresql and SQLAlchemy as the database. This is probably going to change rather soon as I integrate more data."
        }
      />
      <Question
        question={"What is the Leaderboard about?"}
        text={
          "A lot of smart people like baseball and I think the challenge to predict games is a blast. I'll be implementing some basic predictive models so users can not only compete against each other but also against models. Eventually I will be allowing submissions of models to join the competition."
        }
      />
      <Question
        question={
          "Now that the MLB Season is over, what will change for the 2024 launch?"
        }
        text={
          "The statistical features will continue to improve as the off season rolls along. The Blog is going to get a lot of attention and you may be interested in some of the Winter Leauge content"
        }
      />
      <Question
        question={
          "There's a bug / site issue"
        }
        text={
          "Please reach out to me with your username and any details if you see or suspect a bug, the more bugs we squash together the better the site gets, so thank you for reaching out."
        }
      />
      <Question
        question={"What happened to Advanced Fielding?"}
        text={
          "My data source no longer allows the requests that I used to calculate fielding metrics. This feature will return hopefully during spring training."
        }
      />
      <Question
        question={"I have an idea!"}
        text={
          "Please reach out, I'm very interested in seeing what people want implemented."
        }
      />

      <div className="WrapperQuestion">
        <h3 className="QuestionHeader">
          Why haven't you included the game Odds from various gambling sites?
        </h3>
        <p>
          As a one time student of Discrete math the first thing you're taught
          is{" "}
          <a href="https://en.wikipedia.org/wiki/Gambler%27s_ruin">
            Gambler's Ruin{" "}
          </a>
          I actually hope the itch to gamble is somewhat less for people that
          have an outlet (this site) to test their predictive ability. I may
          include the odds generated by ESPN or 538 if they restart their MLB
          project but as of now it's not on the horizon{" "}
        </p>
      </div>
    </div>
  );
}
