"""Reverting non nullable status on game winner and game loserwhich was wrongfully changed

Revision ID: 1390ed42907c
Revises: f2d6ebadeedf
Create Date: 2025-04-17 17:15:51.158972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1390ed42907c'
down_revision = 'f2d6ebadeedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('gameWinner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gameLoser_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('gameLoser_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gameWinner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
