"""added fields to game model

Revision ID: 153559f7fd2e
Revises: 1390ed42907c
Create Date: 2025-04-18 01:31:07.649713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153559f7fd2e'
down_revision = '1390ed42907c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('home_team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('away_team_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('away_team_id')
        batch_op.drop_column('home_team_id')
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
