"""re added fk constraints, changed games

Revision ID: 20ccfad81982
Revises: e1915e1b4d92
Create Date: 2023-10-10 01:15:48.064568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ccfad81982'
down_revision = 'e1915e1b4d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gameResolved', sa.Boolean(), nullable=True))
        batch_op.alter_column('gameWinner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gameLoser_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('gameLoser_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gameWinner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('gameResolved')

    # ### end Alembic commands ###
