"""added stale_game_pull_counter to game and access_level to user

Revision ID: 237963f36e07
Revises: fddcd6a728a8
Create Date: 2024-02-13 01:45:01.450896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237963f36e07'
down_revision = 'fddcd6a728a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stale_game_pull_counter', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('access_level')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('stale_game_pull_counter')

    # ### end Alembic commands ###
