"""Made gameResolved not nullable

Revision ID: 37de1d6ca8c1
Revises: 123fa63ee1aa
Create Date: 2024-01-02 22:34:12.287285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37de1d6ca8c1'
down_revision = '123fa63ee1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('gameResolved',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('gameResolved',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
