"""Create tables owners, pets

Revision ID: 56e21b1a81c9
Revises: f299de70c5ec
Create Date: 2023-09-08 23:34:32.853396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e21b1a81c9'
down_revision = 'f299de70c5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isResolved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.drop_column('isResolved')

    # ### end Alembic commands ###
