"""added game_sport_id to help with different league predictions

Revision ID: 8139798efe04
Revises: 153559f7fd2e
Create Date: 2025-04-30 04:43:30.686348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8139798efe04'
down_revision = '153559f7fd2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_sport_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('game_sport_id')

    # ### end Alembic commands ###
