"""removed fk constains

Revision ID: 8d88e1b3d511
Revises: e821939ce66d
Create Date: 2023-10-09 02:02:33.314420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d88e1b3d511'
down_revision = 'e821939ce66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.alter_column('game_Id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_Id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_user_predictions_user_Id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_user_predictions_game_Id_games', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_predictions_game_Id_games', 'games', ['game_Id'], ['id'])
        batch_op.create_foreign_key('fk_user_predictions_user_Id_users', 'users', ['user_Id'], ['id'])
        batch_op.alter_column('user_Id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('game_Id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
