"""Added gameType, gameSeason and gameDayNight

Revision ID: ad5e382fd250
Revises: 63fa45c6a090
Create Date: 2025-03-01 23:23:34.009661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5e382fd250'
down_revision = '63fa45c6a090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gameType', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gameSeason', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gameDayNight', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('gameDayNight')
        batch_op.drop_column('gameSeason')
        batch_op.drop_column('gameType')

    # ### end Alembic commands ###
