"""made sport id non nullable after updating prior records in database so avoid a conflict

Revision ID: c75f92b8da45
Revises: 8139798efe04
Create Date: 2025-04-30 17:42:27.704002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75f92b8da45'
down_revision = '8139798efe04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('game_sport_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('game_sport_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
