"""re added fk constraints

Revision ID: e1915e1b4d92
Revises: 8d88e1b3d511
Create Date: 2023-10-09 23:25:09.403342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1915e1b4d92'
down_revision = '8d88e1b3d511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.alter_column('game_Id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_Id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_user_predictions_game_Id_games'), 'games', ['game_Id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_predictions_user_Id_users'), 'users', ['user_Id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_predictions_user_Id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_predictions_game_Id_games'), type_='foreignkey')
        batch_op.alter_column('user_Id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('game_Id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
