"""started again, need to run scripts

Revision ID: f299de70c5ec
Revises: 
Create Date: 2023-08-24 23:03:53.124871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f299de70c5ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamePk', sa.Integer(), nullable=False),
    sa.Column('gameWinner_id', sa.Integer(), nullable=False),
    sa.Column('gameLoser_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gamePk')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('currentTeamId', sa.Integer(), nullable=False),
    sa.Column('firstLastName', sa.String(), nullable=False),
    sa.Column('mlbId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlbId')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profilePic', sa.String(), nullable=True),
    sa.Column('totalScore', sa.Integer(), nullable=True),
    sa.Column('totalNumGuesses', sa.Integer(), nullable=True),
    sa.Column('totalGuessesCorrect', sa.Integer(), nullable=True),
    sa.Column('totalGuessesIncorrect', sa.Integer(), nullable=True),
    sa.Column('currentStreak', sa.Integer(), nullable=True),
    sa.Column('longestStreak', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_Id', sa.Integer(), nullable=True),
    sa.Column('user_Id', sa.Integer(), nullable=True),
    sa.Column('predictedWinnerId', sa.Integer(), nullable=False),
    sa.Column('actualWinnerId', sa.Integer(), nullable=True),
    sa.Column('predictedLoserId', sa.Integer(), nullable=False),
    sa.Column('actualLoserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_Id'], ['games.id'], name=op.f('fk_user_predictions_game_Id_games')),
    sa.ForeignKeyConstraint(['user_Id'], ['users.id'], name=op.f('fk_user_predictions_user_Id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_predictions')
    op.drop_table('users')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
