"""Added validation to username, password and improved email form validation, added time stamps to user and prediction on creation time

Revision ID: f2d6ebadeedf
Revises: b43352ae4df0
Create Date: 2025-04-17 15:46:02.818841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d6ebadeedf'
down_revision = 'b43352ae4df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('gameWinner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gameLoser_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gameType',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('gameSeason',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gameDayNight',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('profilePic',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profilePic',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_predictions', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('gameDayNight',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('gameSeason',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gameType',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('gameLoser_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gameWinner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
